server:
  port: 8081
  servlet:
    context-path: '/epead-authuser/'

spring:
  application:
    name: epead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5434/ead-authuser-v2
    username: postgres
    password: elson
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.nom-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enable: Always
  rabbitmq:
    addresses: amqps://aaemzplb:N0eBX_-lVBUi4p8ciod7l3ehubU5i2Gb@moose.rmq.cloudamqp.com/aaemzplb

logging:
  level:
    com.epead : TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

epead:
  api:
    url:
      course: 'http://epead-course-service/epead-course'
  broker:
    exchange:
      userEvent: epead.userevent

authuser:
  refreshscope:
    name: Elson Pinheiro Updade !!!!

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s
