server:
  port: 8084
  servlet:
    context-path: '/epead-notification/'

spring:
  application:
    name: epead-notification-service
  datasource:
      url: jdbc:postgresql://localhost:5434/epead-notification-v2
      username: postgres
      password: elson
  jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.nom-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
      addresses: amqps://aaemzplb:N0eBX_-lVBUi4p8ciod7l3ehubU5i2Gb@moose.rmq.cloudamqp.com/aaemzplb

logging:
  level:
    com.epead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

epead:
  broker:
    exchange:
      notificationCommandExchange: epead.notificationcommand
    queue:
      notificationCommandQueue:
        name: epead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
